### PR TITLE
deps(hugo): Upgrade to v0.102.3

### PR DESCRIPTION
**Pull request by simar7**
Hold onto merging until https://github.com/peaceiris/actions-hugo/issues/605 is merged.

Signed-off-by: Simar <simar@linux.com>

### CODE REVIEW

**Comment by simar7** [comment]
@DmitriyLewen since you are here, do you think we should at some point bump Hugo? I'm sure the newer versions would reduce build time thereby reducing GitHub Actions runner time.

**Comment by DmitriyLewen** [comment]
I used `hugo v0.121.0` on my local PC to create a local site.
This still requires a lot of time and resources, but I haven't noticed any problems with the vulnerability pages.

So, I think we can try to bump `hugo`.

**Comment by simar7** [comment]
> I used `hugo v0.121.0` on my local PC to create a local site.
> 
> This still requires a lot of time and resources, but I haven't noticed any problems with the vulnerability pages.
> 
> 
> 
> So, I think we can try to bump `hugo`.
> 
> 
> 
> @simar7 But this PR is outdated.

I see thanks for checking.

Did your local full build take less time with the recent version of Hugo?

**Comment by DmitriyLewen** [comment]
> Did your local full build take less time with the recent version of Hugo?

I only worked with this version, but I can try to check.

**Comment by simar7** [comment]
> > Did your local full build take less time with the recent version of Hugo?
> 
> I only worked with this version, but I can try to check.

Did you have any update @DmitriyLewen

**Comment by DmitriyLewen** [comment]
Hello @simar7 
Sorry, i was busy with other tasks.

I tried to check this, but my Mac killed `hugo` 😄 :
```bash
➜  time hugo --destination=docs      
Start building sites … 
hugo v0.121.0-e321c3502aa8e80a7a7c951359339a985f082757+extended darwin/arm64 BuildDate=2023-12-05T15:22:31Z VendorInfo=brew

[2]    70243 killed     hugo --destination=docs
hugo --destination=docs  522.21s user 382.57s system 112% cpu 13:25.25 total
```

I wanted to compare time in CI/CD of my fork, but `hugo-action` still didn't fix https://github.com/peaceiris/actions-hugo/issues/605.
Latest possible version for MacOS is `0.101.0`.

Do you have any info why we use `macos` runner to build site?

**Comment by DmitriyLewen** [comment]
I compare currently version with `0.101.0`. `0.101.0` is faster:
`0.81.0` worked 32 min and was killed - https://github.com/DmitriyLewen/avd-generator/actions/runs/9090148356/job/24982466479#step:18:8
`0.101.0` created site for 28 min - https://github.com/DmitriyLewen/avd-generator/actions/runs/9090338993/job/24982997298#step:18:1

**Comment by nikpivkin** [comment]
I tried to run site generation locally, but it eats up all my machine resources :)

**Comment by simar7** [comment]
> Do you have any info why we use `macos` runner to build site?

@DmitriyLewen it actually used to be the case that the macOS runners were more powerful in compute and memory as compared to their linux counterparts. So we moved from linux to macOS. 

But I just checked, it seems that the linux ones have also caught up and now actually offer more https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories. Also the latest Mac runners (macOS-14) are now M1 based instead of the older intel ones. 


It would be worth to try out using both macOS-14 and the linux runners again.

**Comment by DmitriyLewen** [comment]
> @DmitriyLewen I tried to run site generation locally, but it eats up all my machine resources :)

Same case 😞 

> It would be worth to try out using both macOS-14 and the linux runners again.

Let's try using Linux first.

**Comment by simar7** [comment]
Superseded by https://github.com/aquasecurity/avd-generator/commit/e5aaf2f1d9217d66a054f970ad46079696e88943

**Pull request closed without merging**
